-- MySQL Script generated by MySQL Workbench
-- 2017年01月04日 星期三 23时55分41秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sun
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sun
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sun` DEFAULT CHARACTER SET utf8 ;
USE `sun` ;

-- -----------------------------------------------------
-- Table `sun`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sun`.`article` (
  `id` INT(64) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL COMMENT '文章标题',
  `imgsrc` VARCHAR(1000) NULL,
  `create_time` VARCHAR(45) NULL,
  `digest` VARCHAR(200) NULL COMMENT '摘要',
  `link` VARCHAR(500) NULL COMMENT '链接',
  `path` VARCHAR(1000) NULL COMMENT '路径(仅限原创blog)',
  `type` SMALLINT(6) NULL COMMENT '文章类型 0分享，1原创',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
